import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/images/logo.png",
  },
};

const modernMegra = localFont({
  src: '../public/fonts/Modern.ttf',
  variable: '--font-modern-negra',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${modernMegra.variable} antialiased `}
      >
        {children}
      </body>
    </html>
  );
}
